'use client';
import { useEffect, useState } from 'react';
import { Clock3, MapPin, PackageCheck, ShieldCheck, Sparkles, Truck } from 'lucide-react';
type ShippingZone = { id: string; governorate: string; city?: string | null; price: string | number; freeAbove?: string | number | null; etaMinDays?: number | null; etaMaxDays?: number | null };
export default function ShippingPolicyPage() {
  const [zones, setZones] = useState<ShippingZone[]>([]); const [loading, setLoading] = useState(true);
  useEffect(() => { let mounted = true; fetch('/api/shipping').then(res => res.ok ? res.json() : []).then(data => mounted && setZones(Array.isArray(data) ? data : [])).catch(() => mounted && setZones([])).finally(() => mounted && setLoading(false)); return () => { mounted = false; }; }, []);
  const money = (value: string | number | null | undefined) => value == null ? 'حسب المنطقة' : `${Number(value).toLocaleString('ar-EG')} ج.م`;
  return <main className="wahaj-policy-page" dir="rtl"><div className="wahaj-policy-shell"><header className="wahaj-policy-hero"><div className="wahaj-policy-hero__copy"><span className="wahaj-policy-kicker"><Sparkles size={15} /> وَهَج · التوصيل</span><h1>سياسة الشحن</h1><p>نوصّل اختياراتك بعناية ووضوح، مع إظهار تكلفة الشحن ومدة التوصيل قبل تأكيد الطلب.</p></div><span className="wahaj-policy-hero__icon"><Truck size={45} strokeWidth={1.25} /></span></header><div className="wahaj-policy-grid"><section className="wahaj-policy-main"><div className="wahaj-policy-heading"><span>كل ما تحتاجين معرفته</span><h2>تفاصيل التوصيل</h2></div><div className="wahaj-policy-block"><span className="wahaj-policy-block__icon"><MapPin size={20} /></span><div><h3>نطاق وتكلفة الشحن</h3><p>نقوم بالشحن إلى جميع المحافظات المتاحة في إعدادات المتجر. تظهر تكلفة الشحن النهائية بكل شفافية ضمن خطوات إتمام الطلب وقبل تأكيده.</p></div></div><div className="wahaj-policy-block"><span className="wahaj-policy-block__icon"><Clock3 size={20} /></span><div><h3>متوسط أيام التوصيل</h3><p>يستغرق توصيل الطلبات عادةً ما بين 2 إلى 5 أيام عمل بحسب المحافظة أو المدينة وظروف شركة الشحن. قد نتواصل معك لتأكيد بيانات الطلب قبل إرساله.</p></div></div><div className="wahaj-policy-block"><span className="wahaj-policy-block__icon"><PackageCheck size={20} /></span><div><h3>متابعة الشحنة</h3><p>للاستفسار عن حالة طلب قائم أو متابعة خط سير الشحنة، يرجى التواصل مع فريق خدمة العملاء عبر صفحة تواصل معنا.</p></div></div></section><aside className="wahaj-shipping-zones"><div className="wahaj-policy-heading"><span>حسب إعدادات المتجر</span><h2>مناطق الشحن</h2></div>{loading ? <div className="wahaj-policy-loading">جارٍ تحميل المناطق...</div> : zones.length ? <div className="wahaj-zone-list">{zones.map(zone => <div className="wahaj-zone-card" key={zone.id}><div><b><MapPin size={14} />{zone.governorate}</b>{zone.city && <small>{zone.city}</small>}</div><strong>{money(zone.price)}</strong><small>{zone.etaMinDays && zone.etaMaxDays ? `${zone.etaMinDays}–${zone.etaMaxDays} أيام` : 'المدة تظهر عند الطلب'}</small>{zone.freeAbove != null && <em>شحن مجاني فوق {money(zone.freeAbove)}</em>}</div>)}</div> : <p className="wahaj-policy-muted">تظهر تكلفة الشحن التفصيلية حسب عنوانك أثناء إتمام الطلب.</p>}</aside></div><section className="wahaj-policy-trust"><ShieldCheck size={24} /><div><b>وضوح قبل التأكيد</b><p>ستظهر لك تكلفة الشحن النهائية قبل إتمام طلبك، ولن توجد أي رسوم غير معلنة.</p></div></section></div></main>;
}
