import { CheckCircle2, FileText, Info, PhoneCall, ShieldCheck } from 'lucide-react';

export const metadata = { title: 'الشروط والأحكام — وَهَج', description: 'الشروط والأحكام العامة لمتجر وَهَج.' };

const sections = [
  { number: '01', title: 'أولاً: دقة البيانات والمسؤولية الشخصية', icon: CheckCircle2, paragraphs: ['تلتزم العميلة بتقديم بيانات صحيحة، دقيقة، وكاملة (بما في ذلك اسم المستلم، عنوان التوصيل، ورقم الهاتف) عند إنشاء الطلب أو التسجيل في المتجر.', 'تتحمل العميلة وحدها المسؤولية الكاملة عن أي تأخير أو خطأ في تنفيذ أو توصيل الطلب ناشئ عن تقديم بيانات غير دقيقة أو ناقصة.'] },
  { number: '02', title: 'ثثانياً: الأسعار، المخزون، والعروض', icon: FileText, paragraphs: ['تُعد كافة الأسعار، وحجم المخزون، والعروض الترويجية المعلنة قابلة للتعديل أو التغيير من قبل إدارة المتجر في أي وقت دون إشعار مسبق.', 'يُعتد حصرياً بالسعر الظاهر والمثبت في الفكرة النهائية وقت تأكيد الطلب وإتمام عملية الدفع بنجاح، ولا تسرّي أي تعديلات لاحقة على الطلبات المؤكدة مسبقاً.'] },
  { number: '03', title: 'ثالثاً: التواصل والصلاحيات الإدارية', icon: PhoneCall, paragraphs: ['تحتفظ إدارة متجر "وَهَج" بالحق الكامل في التواصل مع العميلة عبر وسائل الاتصال المتاحة (رقم الهاتف، البريد الإلكتروني، أو تطبيق الواتساب) بهدف تأكيد الطلب، أو التحقق من البيانات، أو معالجة أي إشكالية طارئة مرتبطة بعمليات التوصيل أو الدفع.', 'يحق للمتجر تعليق أو إلغاء أي طلب في حال تعذر التواصل مع العميلة أو في حال الاشتباه بعدم صحة البيانات المقدمة، دون أدنى مسؤولية قانونية على المتجر.'] },
];

export default function TermsPage() {
  return <main className="wahaj-terms-page" dir="rtl"><div className="wahaj-terms-shell"><header className="wahaj-terms-hero"><div><span className="wahaj-policy-kicker"><ShieldCheck size={15} /> وَهَج · الشفافية والثقة</span><h1>الشروط والأحكام</h1><p>نوضح لكِ القواعد العامة المنظمة لاستخدام متجر وَهَج وإنشاء الطلبات، لتكون تجربتك واضحة وآمنة.</p></div><span className="wahaj-terms-hero__icon"><FileText size={45} strokeWidth={1.25} /></span></header><section className="wahaj-terms-intro"><Info size={21} /><p>الشروط والأحكام العامة لمتجر <strong>"وَهَج"</strong><br />بوصولكِ إلى متجر "وَهَج" أو استخدامكِ له بأي شكل من الأشكال، فإنكِ تقرين وتوافقين دون قيود أو شروط على الالتزام بكافة الشروط والأحكام الواردة أدناه، وتُعد هذه الأحكام اتفاقية قانونية ملزمة بينكِ وبين إدارة المتجر:</p></section><section className="wahaj-terms-document">{sections.map(({ number, title, icon: Icon, paragraphs }) => <article key={number} className="wahaj-terms-section"><div className="wahaj-terms-number">{number}</div><div className="wahaj-terms-section__body"><div className="wahaj-terms-section__title"><span><Icon size={19} /></span><h2>{title}</h2></div>{paragraphs.map(paragraph => <p key={paragraph}>{paragraph}</p>)}</div></article>)}</section><footer className="wahaj-terms-note"><ShieldCheck size={22} /><div><b>قراءة الشروط تعني وضوح التعامل</b><p>نحرص في وَهَج على تقديم تجربة شراء واضحة، ويمكنك التواصل معنا عند وجود أي استفسار.</p></div></footer></div></main>;
}
